### ISSUE TITLE
vaadin-grid 1.2

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-elements#10]
Tracking issue for the 1.2 minor version of vaadin-grid, with the following sub-tasks:

- [ ] [Improved row detail experience](https://github.com/vaadin/vaadin-grid/issues/166)
- [ ] [Visual regression testing](https://github.com/vaadin/vaadin-grid/issues/176)
- [ ] [Theming/cross-scope styling](https://github.com/vaadin/vaadin-grid/pull/93)
- [ ] [Column reordering](https://github.com/vaadin/vaadin-grid/issues/181)
- [ ] [Column resizing](https://github.com/vaadin/vaadin-grid/issues/145)
- [ ] [Customizable selection model](https://github.com/vaadin/vaadin-grid/issues/182)
- [ ] Improved accessibility support
- [ ] User testing

**Comment by jounik** [comment]
Closing as irrelevant. We will consider the feature set for upcoming versions once we actually have some new features ready.
